[LegalNotice]
Accepted=true

[Preferences]
WebUI\Address=*
WebUI\ServerDomains=*
WebUI\HostHeaderValidation=false
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=0.0.0.0/0, ::/0
WebUI\CSRFProtection=false
